services:
  # Servidor Web Apache + PHP
  web:
    image: php:8.3-apache
    container_name: entorno_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html

  # Base de Datos MariaDB
  db:
    image: mariadb:latest
    container_name: entorno_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba_db
    volumes:
      - datos_db:/var/lib/mysql

  # Interfaz gráfica phpMyAdmin
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: entorno_pma
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

volumes:
  datos_db: